apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: expense-tracker
  source:
    repoURL: https://github.com/damirtat/ExpenseTrackerGitOps.git
    targetRevision: main
    path: platform/edge
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
