apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: expense-tracker
  source:
    path: .
    repoURL: oci://docker.io/envoyproxy/gateway-helm
    targetRevision: v1.8.3
    helm:
      releaseName: envoy-gateway
      valuesObject:
        crds:
          enabled: true
        deployment:
          envoyGateway:
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
