apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: expense-tracker-dev
  namespace: argocd
  annotations:
    # The AppProject is created by the root application at sync wave -10.
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: expense-tracker
  source:
    repoURL: https://github.com/damirtat/ExpenseTrackerGitOps.git
    targetRevision: main
    path: environments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: expense-tracker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
